/*
  DATOS FICTICIOS DEL PROTOTIPO
  INTEGRACIÓN FUTURA: sustituir por consultas autorizadas a la API.
  Catálogo provisional de tipos de trabajo pendiente de aprobación.
  Los IDs permiten usar la misma lista en filtros, reportes y la futura app móvil.
*/
window.RIETI_WORK_TYPES = Object.freeze([
  {
    "id": "venta",
    "label": "Venta ambulante en calles o semáforos"
  },
  {
    "id": "limpieza",
    "label": "Limpieza de parabrisas"
  },
  {
    "id": "comercio",
    "label": "Comercio en mercados o locales"
  },
  {
    "id": "agricola",
    "label": "Trabajo agrícola"
  },
  {
    "id": "construccion",
    "label": "Construcción"
  },
  {
    "id": "domestico",
    "label": "Trabajo doméstico"
  }
]);
window.RIETI_REPORTS = Object.freeze({
  "RIETI-NAU-2026-0001": {
    "id": "RIETI-NAU-2026-0001",
    "status": "Recibido",
    "priority": "Alta",
    "reportedAt": "22/10/2026 15:32",
    "updatedAt": "22/10/2026 15:38",
    "reporter": "Juan López García",
    "email": "reporte.0001@example.com",
    "phone": "+52 55 0000 0001",
    "municipality": "Naucalpan de Juárez",
    "address": "Calle del Parque 24, colonia Centro, Naucalpan de Juárez, Estado de México. Dirección ficticia.",
    "reference": "No especificado",
    "latitude": "19.478000",
    "longitude": "-99.239000",
    "children": "2",
    "ages": "8 y 10 años",
    "workType": "Venta ambulante en calles o semáforos",
    "workHours": "8:00 a. m. – 6:00 p. m.",
    "observations": "Se reporta la participación de dos niños en actividades de venta ambulante en calles o semáforos durante la jornada, sin supervisión adulta visible. Observación ficticia pendiente de verificación.",
    "adminEmail": "administrador@example.com",
    "workTypeId": "venta",
    "authority": "Sin asignar"
  },
  "RIETI-TLA-2026-0002": {
    "id": "RIETI-TLA-2026-0002",
    "status": "Recibido",
    "priority": "Baja",
    "reportedAt": "13/10/2026 18:22",
    "updatedAt": "13/10/2026 18:28",
    "reporter": "Raúl Pérez Hernández",
    "email": "reporte.0002@example.com",
    "phone": "+52 55 0000 0002",
    "municipality": "Tlalnepantla de Baz",
    "address": "Calle del Parque 24, colonia Centro, Tlalnepantla de Baz, Estado de México. Dirección ficticia.",
    "reference": "No especificado",
    "latitude": "19.540000",
    "longitude": "-99.195000",
    "children": "2",
    "ages": "8 y 10 años",
    "workType": "Limpieza de parabrisas",
    "workHours": "8:00 a. m. – 6:00 p. m.",
    "observations": "Se reporta la participación de dos niños en actividades de limpieza de parabrisas durante la jornada, sin supervisión adulta visible. Observación ficticia pendiente de verificación.",
    "adminEmail": "administrador@example.com",
    "workTypeId": "limpieza",
    "authority": "Sin asignar"
  },
  "RIETI-NAU-2026-0003": {
    "id": "RIETI-NAU-2026-0003",
    "status": "En proceso",
    "priority": "Media",
    "reportedAt": "06/10/2026 13:45",
    "updatedAt": "06/10/2026 13:51",
    "reporter": "Santiago Hernández López",
    "email": "reporte.0003@example.com",
    "phone": "+52 55 0000 0003",
    "municipality": "Naucalpan de Juárez",
    "address": "Calle del Parque 24, colonia Centro, Naucalpan de Juárez, Estado de México. Dirección ficticia.",
    "reference": "No especificado",
    "latitude": "19.478000",
    "longitude": "-99.239000",
    "children": "2",
    "ages": "8 y 10 años",
    "workType": "Comercio en mercados o locales",
    "workHours": "8:00 a. m. – 6:00 p. m.",
    "observations": "Se reporta la participación de dos niños en actividades de comercio en mercados o locales durante la jornada, sin supervisión adulta visible. Observación ficticia pendiente de verificación.",
    "adminEmail": "administrador@example.com",
    "workTypeId": "comercio",
    "authority": "Sin asignar"
  },
  "RIETI-COA-2026-0004": {
    "id": "RIETI-COA-2026-0004",
    "status": "En proceso",
    "priority": "Media",
    "reportedAt": "28/09/2026 18:45",
    "updatedAt": "28/09/2026 18:51",
    "reporter": "Valeria Martínez García",
    "email": "reporte.0004@example.com",
    "phone": "+52 55 0000 0004",
    "municipality": "Coacalco",
    "address": "Calle del Parque 24, colonia Centro, Coacalco, Estado de México. Dirección ficticia.",
    "reference": "No especificado",
    "latitude": "19.630000",
    "longitude": "-99.111000",
    "children": "2",
    "ages": "8 y 10 años",
    "workType": "Trabajo agrícola",
    "workHours": "8:00 a. m. – 6:00 p. m.",
    "observations": "Se reporta la participación de dos niños en actividades de trabajo agrícola durante la jornada, sin supervisión adulta visible. Observación ficticia pendiente de verificación.",
    "adminEmail": "administrador@example.com",
    "workTypeId": "agricola",
    "authority": "Sin asignar"
  },
  "RIETI-VDC-2026-0005": {
    "id": "RIETI-VDC-2026-0005",
    "status": "En proceso",
    "priority": "Urgente",
    "reportedAt": "22/09/2026 12:45",
    "updatedAt": "22/09/2026 12:51",
    "reporter": "Diego Ramírez Torres",
    "email": "reporte.0005@example.com",
    "phone": "+52 55 0000 0005",
    "municipality": "Villa del Carbón",
    "address": "Calle del Parque 24, colonia Centro, Villa del Carbón, Estado de México. Dirección ficticia.",
    "reference": "No especificado",
    "latitude": "19.727000",
    "longitude": "-99.464000",
    "children": "2",
    "ages": "8 y 10 años",
    "workType": "Construcción",
    "workHours": "8:00 a. m. – 6:00 p. m.",
    "observations": "Se reporta la participación de dos niños en actividades de construcción durante la jornada, sin supervisión adulta visible. Observación ficticia pendiente de verificación.",
    "adminEmail": "administrador@example.com",
    "workTypeId": "construccion",
    "authority": "Sin asignar"
  },
  "RIETI-HUI-2026-0006": {
    "id": "RIETI-HUI-2026-0006",
    "status": "En proceso",
    "priority": "Alta",
    "reportedAt": "16/09/2026 10:00",
    "updatedAt": "16/09/2026 10:06",
    "reporter": "Fernanda Sánchez Morales",
    "email": "reporte.0006@example.com",
    "phone": "+52 55 0000 0006",
    "municipality": "Huixquilucan",
    "address": "Calle del Parque 24, colonia Centro, Huixquilucan, Estado de México. Dirección ficticia.",
    "reference": "No especificado",
    "latitude": "19.360000",
    "longitude": "-99.350000",
    "children": "2",
    "ages": "8 y 10 años",
    "workType": "Trabajo doméstico",
    "workHours": "8:00 a. m. – 6:00 p. m.",
    "observations": "Se reporta la participación de dos niños en actividades de trabajo doméstico durante la jornada, sin supervisión adulta visible. Observación ficticia pendiente de verificación.",
    "adminEmail": "administrador@example.com",
    "workTypeId": "domestico",
    "authority": "Sin asignar"
  },
  "RIETI-NAU-2026-0007": {
    "id": "RIETI-NAU-2026-0007",
    "status": "Pendiente",
    "priority": "Baja",
    "reportedAt": "11/09/2026 10:00",
    "updatedAt": "11/09/2026 10:06",
    "reporter": "Alejandro González Reyes",
    "email": "reporte.0007@example.com",
    "phone": "+52 55 0000 0007",
    "municipality": "Naucalpan de Juárez",
    "address": "Calle del Parque 24, colonia Centro, Naucalpan de Juárez, Estado de México. Dirección ficticia.",
    "reference": "No especificado",
    "latitude": "19.478000",
    "longitude": "-99.239000",
    "children": "2",
    "ages": "8 y 10 años",
    "workType": "Venta ambulante en calles o semáforos",
    "workHours": "8:00 a. m. – 6:00 p. m.",
    "observations": "Se reporta la participación de dos niños en actividades de venta ambulante en calles o semáforos durante la jornada, sin supervisión adulta visible. Observación ficticia pendiente de verificación.",
    "adminEmail": "administrador@example.com",
    "workTypeId": "venta",
    "authority": "Sin asignar"
  },
  "RIETI-TUL-2026-0008": {
    "id": "RIETI-TUL-2026-0008",
    "status": "Resuelto",
    "priority": "Media",
    "reportedAt": "04/09/2026 10:00",
    "updatedAt": "04/09/2026 10:06",
    "reporter": "Camila Rodríguez Flores",
    "email": "reporte.0008@example.com",
    "phone": "+52 55 0000 0008",
    "municipality": "Tultitlán",
    "address": "Calle del Parque 24, colonia Centro, Tultitlán, Estado de México. Dirección ficticia.",
    "reference": "No especificado",
    "latitude": "19.646000",
    "longitude": "-99.170000",
    "children": "2",
    "ages": "8 y 10 años",
    "workType": "Limpieza de parabrisas",
    "workHours": "8:00 a. m. – 6:00 p. m.",
    "observations": "Se reporta la participación de dos niños en actividades de limpieza de parabrisas durante la jornada, sin supervisión adulta visible. Observación ficticia pendiente de verificación.",
    "adminEmail": "administrador@example.com",
    "workTypeId": "limpieza",
    "authority": "Sin asignar"
  },
  "RIETI-ATZ-2026-0009": {
    "id": "RIETI-ATZ-2026-0009",
    "status": "Resuelto",
    "priority": "Urgente",
    "reportedAt": "25/08/2026 10:00",
    "updatedAt": "25/08/2026 10:06",
    "reporter": "Sebastián Castillo Vargas",
    "email": "reporte.0009@example.com",
    "phone": "+52 55 0000 0009",
    "municipality": "Atizapán de Zaragoza",
    "address": "Calle del Parque 24, colonia Centro, Atizapán de Zaragoza, Estado de México. Dirección ficticia.",
    "reference": "No especificado",
    "latitude": "19.557000",
    "longitude": "-99.267000",
    "children": "2",
    "ages": "8 y 10 años",
    "workType": "Comercio en mercados o locales",
    "workHours": "8:00 a. m. – 6:00 p. m.",
    "observations": "Se reporta la participación de dos niños en actividades de comercio en mercados o locales durante la jornada, sin supervisión adulta visible. Observación ficticia pendiente de verificación.",
    "adminEmail": "administrador@example.com",
    "workTypeId": "comercio",
    "authority": "Sin asignar"
  },
  "RIETI-COA-2026-0010": {
    "id": "RIETI-COA-2026-0010",
    "status": "Pendiente",
    "priority": "Baja",
    "reportedAt": "20/08/2026 10:00",
    "updatedAt": "20/08/2026 10:06",
    "reporter": "Mariana Cruz Mendoza",
    "email": "reporte.0010@example.com",
    "phone": "+52 55 0000 0010",
    "municipality": "Coacalco",
    "address": "Calle del Parque 24, colonia Centro, Coacalco, Estado de México. Dirección ficticia.",
    "reference": "No especificado",
    "latitude": "19.630000",
    "longitude": "-99.111000",
    "children": "2",
    "ages": "8 y 10 años",
    "workType": "Trabajo agrícola",
    "workHours": "8:00 a. m. – 6:00 p. m.",
    "observations": "Se reporta la participación de dos niños en actividades de trabajo agrícola durante la jornada, sin supervisión adulta visible. Observación ficticia pendiente de verificación.",
    "adminEmail": "administrador@example.com",
    "workTypeId": "agricola",
    "authority": "Sin asignar"
  },
  "RIETI-CIZ-2026-0003": {
    "id": "RIETI-CIZ-2026-0003",
    "status": "En proceso",
    "priority": "Media",
    "reportedAt": "06/10/2026 13:45",
    "updatedAt": "06/10/2026 13:51",
    "reporter": "Santiago Hernández López",
    "email": "reporte.0003@example.com",
    "phone": "+52 55 0000 0003",
    "municipality": "Cuautitlán Izcalli",
    "address": "Calle del Parque 24, colonia Centro, Cuautitlán Izcalli, Estado de México. Dirección ficticia.",
    "reference": "No especificado",
    "latitude": "19.645000",
    "longitude": "-99.209000",
    "children": "2",
    "ages": "8 y 10 años",
    "workType": "Construcción",
    "workHours": "8:00 a. m. – 6:00 p. m.",
    "observations": "Se reporta la participación de dos niños en actividades de construcción durante la jornada, sin supervisión adulta visible. Observación ficticia pendiente de verificación.",
    "adminEmail": "administrador@example.com",
    "workTypeId": "construccion",
    "authority": "Sin asignar"
  }
});
